Iss 104 intro vignette
SchlossLab/mikropml pull request #216
Opened 2020-10-28 21:28 UTC by zenalapp

If you all could modify as you wish/provide feedback, that'd be great! This doesn't resolve all of #104 but it gets us closer!

To resolve it I think we need:
- Better documentation of actual run_ml function
- Vignette about default hyperparameters and tuning hyperparameters

2020-10-29 20:45 UTC, kelly-sovacool requested changes
Let's resolves the TO-DOs before we merge

2020-11-02 22:22 UTC, BTopcuoglu approved these changes
Looks good. I made some additions/changes.

2020-11-12 23:38 UTC, kelly-sovacool commented
I think this is ready once the pr_build finishes

2020-11-13 15:15 UTC, kelly-sovacool approved these changes

2020-11-13 15:54 UTC, merged